#!/bin/sh
#
#          ██   ██      ██
#   █████ ░░   ░██     ░░
#  ██░░░██ ██ ██████    ██  ██████
# ░██  ░██░██░░░██░    ░██ ██░░░░██
# ░░██████░██  ░██     ░██░██   ░██
#  ░░░░░██░██  ░██     ░██░██   ░██
#   █████ ░██  ░░██  ██░██░░██████
#  ░░░░░  ░░    ░░  ░░ ░░  ░░░░░░
#
# create short / vanity github urls
#         ▟▙
# ▟▒░░░░░░░▜▙▜████████████████████████████████▛
# ▜▒░░░░░░░▟▛▟▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▛
#         ▜▛
# xero / syntax-samurai <http://git.io/gitio.sh>

URLREGX='(https?|http)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]'
GHURL=
VANITY=

usage () {
    cat <<EOF

         ▟▙
 ▟▒░░░░░░░▜▙▜████████████████████████████████▛
 ▜▒░░░░░░░▟▛▟▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▛
         ▜▛

 create short / vanity github urls
 usage: $(basename $0) http://github.com/something [-v mini]
 
 options:
  -v   shortlink
  -h   display this screen
EOF
	exit 0
}

err() {
	echo $1
	usage	
}

optstest() {
	FOUND=0
	for var in "$@"
	do
		if [[ $var =~ $URLREGX ]]
		then
			GHURL=$var
			FOUND=1
		elif [[ $var == "-h" ]]
		then
			usage
		elif [[ $var == "-v" ]]
		then
			X=
		else
			VANITY=$var
		fi
	done
	if (( FOUND == 0 ))
	then
		err " must be a valid github.com url!"
	fi
}

case $# in
	1)
		optstest $1 ;;
	3)
		optstest $1 $2 $3 ;;
	*)
		err " invalid number of arguments!" ;;
esac

if [ -z "$VANITY" ]
then
	curl -i http://git.io -F "url=$GHURL"
else
	curl -i http://git.io -F "url=$GHURL" -F "code=$VANITY"
fi
